export const languageCode = [
    ["arb", "Arabic"],
    ["cmn-CN", "Chinese, Mandarin"],
    ["cy-GB", "Welsh (United Kingdom)"],
    ["da-DK", "Danish (Denmark)"],
    ["en-AU", "English (Australia)"],
    ["en-GB", "English (United Kingdom)"],
    ["en-GB-WLS", "English, Welsh"],
    ["en-IN", "English (Indian)"],
    ["en-US", "English (US)"],
    ["es-ES", "Spanish (European)"],
    ["es-MX", "Spanish (Mexican)"],
    ["es-US", "Spanish (US)"],
    ["fr-CA", "French (Canadian)"],
    ["fr-FR", "French"],
    ["is-IS", "Icelandic"],
    ["it-IT", "Italian"],
    ["ja-JP", "Japanese"],
    ["hi-IN", "Hindi"],
    ["ko-KR", "Korean"],
    ["nb-NO", "Norwegian"],
    ["nl-NL", "Dutch"],
    ["pl-PL", "Polish"],
    ["pt-BR", "Portuguese (Brazilian)"],
    ["pt-PT", "Portuguese (European)"],
    ["ro-RO", "Romanian"],
    ["ru-RU", "Russian"],
    ["sv-SE", "Swedish"],
    ["tr-TR", "Turkish"],
]